[package]
name = "hn"
version = "0.1.0"
authors = ["Michael Simpson <michael@snthesis.com>"]
edition = "2018"

[dependencies]
colored = "1"
reqwest = { version = "0.10", features = ["blocking"] }
scraper = "0.11"
