[package]
authors = ["Michael Simpson <michael@snthesis.com>"]
edition = "2018"
name = "hn"
version = "0.1.0"

[dependencies]
colored = "2"
reqwest = {version = "0.11", features = ["blocking"]}
scraper = "0.12"
